version: "3"
services:
  ubuntu:
    build:
      context: ./build
      dockerfile: Dockerfile
    image: ubuntu:latest
    container_name: vm_can
    tty: true
    stdin_open: true
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    volumes:
      - "./code_rep:/code_rep"
    privileged: true
